Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/LineLength:
  Max: 100

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/Alias:
  Enabled: false

Style/DotPosition:
  Enabled: true
  EnforcedStyle: trailing

Style/SignalException:
  Enabled: false
