Metrics/ClassLength:
  Enabled: false

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Enabled: false

Syle/DotPosition:
  Enabled: true
  EnforcedStyle: trailing

Style/SignalException:
  Enabled: false
